package fi.benjami.code4jvm.lua.ir;

import fi.benjami.code4jvm.Value;
import fi.benjami.code4jvm.block.Block;
import fi.benjami.code4jvm.lua.compiler.LuaContext;
import fi.benjami.code4jvm.statement.DebugInfo;

/**
 * Emits debug information such as line numbers to generated bytecode.
 * Debug info nodes should not otherwise affect execution of code!
 *
 */
public record DebugInfoNode(
		int lineNumber,
		IrNode node
) implements IrNode {

	@Override
	public Value emit(LuaContext ctx, Block block) {
		block.add(DebugInfo.lineNumber(lineNumber));
		return node.emit(ctx, block);
	}

	@Override
	public LuaType outputType(LuaContext ctx) {
		return node.outputType(ctx);
	}
	
	@Override
	public boolean hasReturn() {
		return node.hasReturn();
	}
	
	@Override
	public IrNode concreteNode() {
		return node.concreteNode();
	}

}
